Areas/Admin/Controllers/CategoriesController.cs
using System.Linq;
using System.Threading.Tasks;
using ChaVoV1.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace ChaVo.Areas.Admin.Controllers
{
    public class CategoriesController : AdminHelper
    {
        DataContext _context;
        public CategoriesController(DataContext context)
        {   
            this._context = context;
        }

        public async Task<IActionResult> Index()
        {
            var li = await _context.Categories.ToListAsync();
            return View(li);
        }
        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var model = await _context.Categories.FirstAsync(c=>c.Id == id);
            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(Category model)
        {
            var lastmodel = await _context.Categories.FirstAsync(c=>c.Id == model.Id);
            lastmodel.CategoryText = model.CategoryText;
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }
        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            var model = await _context.Categories.FirstAsync(c=>c.Id == id);
            var QuestionLi = await _context.Questions.Include(q=>q.Category).Where(q=> q.Category.Id == model.Id).ToListAsync();
            foreach (var x in QuestionLi)
            {
                var QuestionModel = await _context.Questions.FirstAsync(q=>q.Id == x.Id);
                var AnswerLi = await _context.Answers.Include(a=>a.Question).Where(a=>a.Question.Id == x.Id).ToListAsync();
                foreach (var answer in AnswerLi)
                {
                    var AnswerModel = await _context.Answers.FirstAsync(a=>a.Id == answer.Id);
                    _context.Answers.Remove(AnswerModel);
                    await _context.SaveChangesAsync();
                }
                _context.Questions.Remove(QuestionModel);
                await _context.SaveChangesAsync();
            }
            _context.Categories.Remove(model);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }
    }
}

Areas/Admin/Controllers/QuestionController.cs
using System;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using ChaVoV1.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace ChaVo.Areas.Admin.Controllers
{
    public class QuestionController : AdminHelper
    {
        DataContext _context;
        public QuestionController(DataContext context)
        {
            this._context = context;
        }
        public IActionResult Index()
        {
            return View();
        }
        public async Task<IActionResult> List()
        {
            ViewBag.Categories = _context.Categories.ToList();
            var li = await _context.Questions.OrderBy(p => p.PubDate).ToListAsync();
            return View(li);
        }
        [HttpPost]
        public async Task<IActionResult> List(int id)
        {
            ViewBag.Categories = _context.Categories.ToList();
            var li = id == 0 ? await _context.Questions.OrderBy(p => p.PubDate).ToListAsync() : await _context.Questions.Include(q => q.Category).Where(q => q.Category.Id == id).OrderBy(p => p.PubDate).ToListAsync();
            return View(li);
        }
        public async Task<IActionResult> Add()
        {
            ViewBag.Categories = await _context.Categories.ToListAsync();
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Add(Question model, int CategoryId)
        {
            model.PubDate = DateTime.Now.Date;
            var _categoryModel = await _context.Categories.SingleAsync(c => c.Id == CategoryId);
            model.Category = _categoryModel;
            _context.Questions.Add(model);
            await _context.SaveChangesAsync();
            return RedirectToAction("List");
        }
        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            try
            {
                var model = await _context.Questions.Include(q => q.Category).SingleAsync(q => q.Id == id);
                ViewBag.Categories = await _context.Categories.OrderByDescending(p => p.Id == model.Category.Id).ToListAsync();
                return View(model);
            }
            catch (Exception ex)
            {
                return RedirectToAction("List");
            }
        }
        [HttpPost]
        public async Task<IActionResult> Edit(Question model, int CategoryId)
        {
            try
            {
                var _categoryModel = await _context.Categories.SingleAsync(c => c.Id == CategoryId);
                var lastmodel = await _context.Questions.SingleAsync(q => q.Id == model.Id);
                lastmodel.Category = _categoryModel;
                lastmodel.QuestionText = model.QuestionText;
                lastmodel.QuestionTitle = model.QuestionTitle;
                await _context.SaveChangesAsync();
            }
            catch (Exception ex)
            {
            }
            return RedirectToAction("List");
        }
        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            var model = await _context.Questions.SingleAsync(q => q.Id == id);
            var li = await _context.Answers.Include(a => a.Question).Where(a=> a.Question.Id == id).ToListAsync();
            foreach (var x in li)
            {
                var answer = await _context.Answers.FirstAsync(c=>c.Id == x.Id);
                _context.Answers.Remove(answer);
                await _context.SaveChangesAsync();
            }
            _context.Questions.Remove(model);
            await _context.SaveChangesAsync();
            return RedirectToAction("List");
        }
    }
}

Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ChaVoV1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/myStyle.css" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/js/jquery.cookie.js"></script>
</head>
<body style="background-color: silver;">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ChaVoV1</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Question" asp-action="List">Questions</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Categories" asp-action="Index">Categories</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - ChaVoV1 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>